### ISSUE TITLE
Doesn't work with webpack 2

### ISSUE THREAD

**Issue by stevenxxiu** [anjianshi/custom-loader#1]
This doesn't work on webpack 2, it complains that the query on line 10 cannot be set due to it being a getter. Webpack 2 got rid of queries more or less I think, so the fix might be backwards-incompatible.

**Comment by anjianshi** [comment]
Thanks for this report, I'll try to fix it.

**Comment by anjianshi** [comment]
@stevenxxiu fixed, have a try :)
